version: "3.8"

services:

  rabbitBanco:
    image: rabbitmq:3-management
    container_name: rabbitBanco
    environment:
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: rabbit
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - cordillera

  serviceConsul:
    image: consul:1.9.10
    container_name: service_discovery
    ports:
      - 8500:8500
    networks:
      - cordillera

  serviceFabio:
    image: fabiolb/fabio:1.5.15-go1.15.5
    container_name: service_balancer
    ports:
      - 9998:9998
      - 9999:9999
    networks:
      - cordillera

  zookeeper:
    image: confluentinc/cp-zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - cordillera

  kafka-broker-1:
    image: confluentinc/cp-kafka
    container_name: kafka-broker-1
    depends_on:
      - zookeeper
    environment:  
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker-1:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    networks:
      - cordillera

networks:
  cordillera:
    external: true