version: "3.5"

services:
  mariadb:
    image: mariadb
    container_name: AD_mariadb
    environment:
      MARIADB_ROOT_PASSWORD:  dennis07@
    ports:
      - "3493:3306"
    networks:
      - cordillera
  

  mongo:
    image: mongo
    container_name: AD_mongo
    environment:
      ME_CONFIG_MONGODB_ADMINPASSWORD:  root
      ME_CONFIG_MONGODB_ADMINUSERNAME:  root
    ports:
      - "8439:27017"
    networks:
      - cordillera

networks:
  cordillera:
    external: true